version: '3.7'

services:
  # NGINX Server-------------------------------------------------------------------------
  nginx:
    image: nginx:1.25.3-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8282:8282"
    volumes:
      - ./index.html:/var/www/html/index.html
      - ./docker/nginx-loop-samplr-io.conf:/etc/nginx/conf.d/default.conf